### ISSUE TITLE
Proposal: Feedback

### ISSUE THREAD

**Issue by s-pangburn** [SkyisAakash/MeetUs#1]
### Homepage
- [x] Generally, your MVP List should be first
- [x] Your links should be a bullet-pointed list, not numbered
- [x] Edit the title from "Home" to "Meetus Proposal" or include "Meetus Proposal" as a heading before your list.

### MVP List
- [x] "Meetus, is a meetup.com clone" <-- comma here is not necessary, also it'd be nice if meetup.com was a link
- [x] Hosting on Heroku should be first, since it is the first thing that should be done chronologically (it's the best way for me to test your app! 🙂 )
- [x] Styling, Seeds, and Smooth navigation should be under all features, consistently
- [x] You should be doing full CRUD for Groups and Events, and should mention that in your proposal. **Actually, looking at the MVP List, I think what they're asking for is a bit unreasonable for the timeline, so feel free to change Calendar into a Bonus and break up Events and RSVPs into two MVPs**

### Schema
- [x] Don't include Categories here for now. Write your tables for the minimum viable product
- [x] `group_id` should be next to `organizer_id in the schema. Just makes it easier to read.
- [x] You probably won't store images in their own tables, especially since it looks like the url is the only column in most of these tables. Just put `img_url` columns in the relevant tables.
- [x] Table names should be `back_ticked_and_snake_case`

### Routes
- [x] You probably want a frontend route for `/groups/:groupId/events`
- [x] Headers (table names) should be `backticked`
- [x] `DELETE` should be capitalized.
- [x] Include a backend route for search!

### Sample State
- [x] Fix indentation!!!
- [x] the top line for your code block should be ```javascript, which will add syntax highlighting
- [x] You have two identical users, which shouldn't be allowed by your database

### Component Hierarchy
- [x] Your headers should be consistently sized
- [x] Be sure to include containers any place where you will be fetching data from the store! (Group show pages, Event pages, edit pages, etc)
- [x] Also, try to list out routes and preliminary ideas for state for components where that is relevant. Doesn't have to be perfect, just give it a first pass (also the routes should match your routes in the Routes section of your proposal, so make sure those are 1:1.)
- [x] Wrap component names in `backticks`

Be sure to get this done sometime before tomorrow so that you can start right on your fullstack! Feel free to reference the [BlueBird wiki](https://github.com/appacademy/bluebird/wiki) as an example of what I mean 🙂

**Comment by SkyisAakash** [comment]
I am going to be using the index method of event and group controllers to do the search. In case of dashboard I plan to keep search criteria to empty string.

**Comment by SkyisAakash** [comment]
I also added `/search/` frontend route

**Comment by s-pangburn** [comment]
Looks good! Great work Aakash!
