### ISSUE TITLE
Search Group/Event by name

### ISSUE THREAD

**Issue by SkyisAakash** [SkyisAakash/MeetUs#4]

**Comment by SkyisAakash** [comment]
try to checkout group bay area cookimg, its got event

**Comment by s-pangburn** [comment]
- [x] The text in the search bar should be a little smaller. Try to make the font size closer to what you see on Meetup.com
- [x] It should search every time I type a character. I should not have to press enter.
- [x] The search icon should be centered in the bar and needs a little more padding on the right.

**Comment by s-pangburn** [comment]
- [x] Also, this goes back to a previous MVP, but your video is a little too bright and at certain parts the text is hard to read. Meetup's website actually darkens their video using CSS. You should take the player div and add this property to it:
`background: rgba(0, 0, 0, 0.50);`
Feel free to change `0.50` to whatever you think is suitable.

If you have any questions, please let me know!

**Comment by s-pangburn** [comment]
Looks good Aakash! Awesome job 🙂
