### ISSUE TITLE
Groups-join/leave/create/delete/show

### ISSUE THREAD

**Issue by SkyisAakash** [SkyisAakash/MeetUs#5]

**Comment by SkyisAakash** [comment]
Profile button works now
I wanted to have atleast one modal

**Comment by s-pangburn** [comment]
- [x] The headers (Meetus Groups you can join & Your Meetus Groups) have way too much padding all around. Too much space. Have only a little bit on the top and bottom, and the text should be aligned left, along the same edge as the tiles below, just like on Meetup.
- [x] Also, make sure "Meetus Groups you can join" is properly capitalized, and either stick to Meetus or MeetUs throughout your website for more consistency.
- [x] When I scroll down on the Events Index page the search bar jumps to the right off the page. I think your CSS needs to be reworked to work with multiple monitor sizes. It shouldn't be this fragile:
![screen shot 2018-06-12 at 10 32 27 am](https://user-images.githubusercontent.com/8031316/41306757-fc43bcd4-6e2b-11e8-9fdb-3bcc7c6e3843.png)
- [x] Same with your Event Show page. The controls are off the screen:
![screen shot 2018-06-12 at 10 33 58 am](https://user-images.githubusercontent.com/8031316/41306821-31200de0-6e2c-11e8-8cf0-a7a4af899605.png)
![screen shot 2018-06-12 at 10 34 06 am](https://user-images.githubusercontent.com/8031316/41306829-33f2218e-6e2c-11e8-9005-4b76c8f2f4a6.png)
- [x] All of your links on the show page go back to the root homepage. This would be a terrible experience for a recruiter poking around. It would even be better if they don't link anywhere at all yet.
- [x] If I join a group and refresh the page, it still says "Join Group" and not "Leave Group"
  - However, if I press the back button and navigate back to the page, it says "Leave Group"???
- [x] Once again, the description text and "What we're about" header should be aligned-left. Ideally, you should use similar or the same fonts as Meetup, at the same sizes.
- [x] Is everything supposed to be pushed to the right like this?
![screen shot 2018-06-12 at 10 41 08 am](https://user-images.githubusercontent.com/8031316/41307130-326a074a-6e2d-11e8-8a7d-c1584f56a911.png)
  - I notice that zooming out seems to help. You need to have your site work at multiple zoom levels.
- [x] The new group page won't let me upload an image. Instead I get an error: `Uncaught Missing required option: cloud_name`. I think you didn't migrate your Cloudinary keys to Heroku. [Here's a reading in the FS curriculum on how to do that](https://github.com/appacademy/curriculum/blob/master/full-stack-project/resources/security/figaro.md).
- [x] The image preview looks a little weird on the actual show page. Maybe try something more like [this?](https://www.google.com/search?tbm=isch&source=hp&biw=1440&bih=803&ei=3AggW-eTI5Gq8APyraSwCw&q=no+image&oq=no+image&gs_l=img.3..0l10.300.1094.0.1216.9.8.0.1.1.0.124.578.5j2.7.0....0...1ac.1.64.img..2.7.469.0...0.WGScAJ_jvas#imgrc=_)

**Comment by s-pangburn** [comment]
For CSS help, use your classmates and Meetup as a reference. You want it to look as close to this as possible!
![screen shot 2018-06-12 at 11 03 51 am](https://user-images.githubusercontent.com/8031316/41308401-9d89b068-6e30-11e8-8174-2fda73fada38.png)

**Comment by s-pangburn** [comment]
- [ ] Also, titles that are multiline should preserve the same amount of padding on the bottom (index page):
![screen shot 2018-06-12 at 11 12 47 am](https://user-images.githubusercontent.com/8031316/41308731-9f3078d8-6e31-11e8-9b54-8abc85b55927.png)

Instead it should be like this:
![screen shot 2018-06-12 at 11 13 53 am](https://user-images.githubusercontent.com/8031316/41308765-b95b74e2-6e31-11e8-8182-a1e9e0624d0e.png)

**Comment by s-pangburn** [comment]
Excellent work Aakash! This looks great! 👍
