### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by SkyisAakash** [SkyisAakash/MeetUs#6]

**Comment by s-pangburn** [comment]
- [x] Style your date and time inputs to use the same font and border as the other inputs
- [x] Same point about the image preview as the groups MVP
- [x] Your Edit Event form doesn't get the date and time properly. I didn't set it again, and my event time was changed to 11:07PM-11:07PM??
- [x] Again, things are too far to the right, and the info div is too squished. The text gets cut off:
![screen shot 2018-06-12 at 10 58 08 am](https://user-images.githubusercontent.com/8031316/41308002-92ef256c-6e2f-11e8-9751-b8e8dd10a098.png)
- [x] Style it to look exactly like Meetup (no calendar is fine, I'm talking about spacing, fonts, everything else):
![screen shot 2018-06-12 at 10 59 03 am](https://user-images.githubusercontent.com/8031316/41308031-a6a8bbcc-6e2f-11e8-8a41-6fcfdbcc9b9d.png)
  - If you need CSS help, feel free to ask your circlemates and classmates for tips!
- [x] On the event show page, the username should not be blue if it is not a link.
- [x] Again, CSS:
![screen shot 2018-06-12 at 11 02 34 am](https://user-images.githubusercontent.com/8031316/41308318-6a2b0758-6e30-11e8-8fb6-3207581d79cf.png)
- [x] Deleting an event should take you back to the group show page, not the index.

**Comment by s-pangburn** [comment]
- [x] This floating side bar thing needs more padding all-around:
![screen shot 2018-06-13 at 2 30 39 pm](https://user-images.githubusercontent.com/8031316/41379269-68d9ef72-6f16-11e8-8077-ea4d0c8af429.png)
- [x] Also, when we're at the top of the page and it's expanded, it just goes sliiightly off the screen. This isn't that big of a deal, but if you could bring it in a little bit I think it would look better:
![screen shot 2018-06-13 at 2 31 39 pm](https://user-images.githubusercontent.com/8031316/41379345-965120d8-6f16-11e8-9378-58c8c6dfcf34.png)

**Comment by s-pangburn** [comment]
Okay! Great job Aakash! I'm marking this MVP as done, but just as general feedback, I think your site would look much, much more professional if your descriptions had proper formatting (spacing, headers, etc.) Might be something to look into in the future!
