### ISSUE TITLE
Event RSVPs

### ISSUE THREAD

**Issue by SkyisAakash** [SkyisAakash/MeetUs#7]

**Comment by s-pangburn** [comment]
- [x] The top bar on this one is also cut off when I scroll down:
![screen shot 2018-06-12 at 11 06 38 am](https://user-images.githubusercontent.com/8031316/41308452-bf9a0694-6e30-11e8-9b72-bf169d895643.png)
  - You might be using a lot of `position: absolute` and `position: relative` in your CSS. I would recommend refactoring to use purely flexbox and margins/padding. Much easier to manage.
- [x] Again, refreshing the page doesn't persist my "going" status, but this time if I navigate back manually it does not persist either. It is always "Are you going?" even if I clicked that I'm going.

**Comment by s-pangburn** [comment]
👏 👏 👏
