### ISSUE TITLE
Bug: Slow performance on group index page

### ISSUE THREAD

**Issue by s-pangburn** [SkyisAakash/MeetUs#8]
This is something kind of separate from my review, but I noticed while browsing around your site that the homepage after you log in (the group index page, that is) is really laggy for some reason, especially when I scroll? Could you look into why this might be happening? Are you using an `onScroll` event or something?

**Comment by SkyisAakash** [comment]
I am using on scroll event handler for making the searchbox fixed position on top when scrolling exceeds certain limit

**Comment by SkyisAakash** [comment]
So I was fetching all the groups on componentWillReceiveProps but now I am doing that on componentWillMount , seems to me it made it a bit better

**Comment by s-pangburn** [comment]
Oh geez! Yeah, that would do it 😟 

I'm surprised it wasn't worse, to be honest. That's basically an infinite loop.

componentWillReceiveProps -> fetchAllGroups -> groups come back -> componentWillReceiveProps -> fetchAllGroups -> ....

- [x] Make sure to push to heroku!
